modLoader="javafml"
loaderVersion="[3,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
displayURL="${mod_homepage}"

[[mixins]]
config="dynamicheight.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[20,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[1.20.5,1.20.6)"
ordering="NONE"
side="BOTH"
